#!/usr/bin/env python3
"""Static site generator for the Blender for Android port site.

Standard library only. No pip install, no venv.

    python tools/build.py                     regenerate the whole site
    python tools/build.py new --track main    scaffold an empty update
    python tools/build.py import <url>        pull a GitHub release into an update

Content lives in content/site.yaml and content/updates/*.md. Everything else on
the site is derived: which release is newest per track, what the download rows
point at, the sizes shown, the feed order. Nothing about a version is written
in two places.
"""

import argparse
import datetime as dt
import html
import json
import os
import re
import shutil
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "content")
UPDATES_DIR = os.path.join(CONTENT, "updates")
PAGES_DIR = os.path.join(CONTENT, "pages")
OUT_UPDATES = os.path.join(ROOT, "updates")

GENERATED_NOTE = "<!-- generated by tools/build.py; edit content/ and rerun -->"


# --------------------------------------------------------------------------
# A small YAML subset: nested maps, lists of scalars, lists of maps, scalars.
# Enough for this project's frontmatter and site config, and nothing more.
# --------------------------------------------------------------------------

def _scalar(raw):
    raw = raw.strip()
    if not raw:
        return ""
    if raw[0] in "\"'" and raw[-1] == raw[0] and len(raw) >= 2:
        return raw[1:-1]
    low = raw.lower()
    if low in ("true", "yes"):
        return True
    if low in ("false", "no"):
        return False
    if low in ("null", "~"):
        return None
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    if re.fullmatch(r"-?\d+\.\d+", raw):
        return float(raw)
    return raw


def _indent_of(line):
    return len(line) - len(line.lstrip(" "))


def parse_yaml(text):
    """Parse the supported subset into Python objects."""
    lines = []
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        lines.append(raw.rstrip())
    value, _ = _parse_block(lines, 0, _indent_of(lines[0]) if lines else 0)
    return value


def _parse_block(lines, i, indent):
    if i >= len(lines):
        return {}, i
    if lines[i].lstrip().startswith("- "):
        return _parse_list(lines, i, indent)
    return _parse_map(lines, i, indent)


def _parse_map(lines, i, indent):
    out = {}
    while i < len(lines):
        line = lines[i]
        cur = _indent_of(line)
        if cur < indent:
            break
        if cur > indent:
            raise ValueError("unexpected indent at: %s" % line.strip())
        stripped = line.strip()
        if stripped.startswith("- "):
            break
        if ":" not in stripped:
            raise ValueError("expected 'key: value' at: %s" % stripped)
        key, _, rest = stripped.partition(":")
        key = key.strip()
        rest = rest.strip()
        if rest == "|":
            # literal block: keep newlines
            i += 1
            buf = []
            while i < len(lines) and _indent_of(lines[i]) > indent:
                buf.append(lines[i][indent + 2:])
                i += 1
            out[key] = "\n".join(buf)
            continue
        if rest == ">":
            # folded block: join into one line
            i += 1
            buf = []
            while i < len(lines) and _indent_of(lines[i]) > indent:
                buf.append(lines[i].strip())
                i += 1
            out[key] = " ".join(buf)
            continue
        if rest == "":
            nxt = i + 1
            if nxt < len(lines) and _indent_of(lines[nxt]) > indent:
                child, i = _parse_block(lines, nxt, _indent_of(lines[nxt]))
                out[key] = child
                continue
            out[key] = ""
            i += 1
            continue
        out[key] = _scalar(rest)
        i += 1
    return out, i


def _parse_list(lines, i, indent):
    out = []
    while i < len(lines):
        line = lines[i]
        cur = _indent_of(line)
        if cur < indent or not line.strip().startswith("- "):
            break
        body = line.strip()[2:]
        if ":" in body and not body.startswith(("http://", "https://")):
            # a map whose first key shares the dash line
            sub_lines = [" " * (indent + 2) + body]
            i += 1
            while i < len(lines) and _indent_of(lines[i]) > indent:
                sub_lines.append(lines[i])
                i += 1
            item, _ = _parse_map(sub_lines, 0, indent + 2)
            out.append(item)
            continue
        out.append(_scalar(body))
        i += 1
    return out, i


# --------------------------------------------------------------------------
# Markdown. A renderer for the syntax these release notes actually use:
# headings, bold, italic, inline code, links, fenced code, lists, tables,
# blockquotes, GitHub alerts and rules. Not a general CommonMark engine.
# --------------------------------------------------------------------------

INLINE_CODE = re.compile(r"`([^`]+)`")
BOLD = re.compile(r"\*\*(.+?)\*\*", re.S)
ITALIC = re.compile(r"(?<![\*\w])\*([^\*\n]+)\*(?!\*)")
IMAGE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+\"([^\"]*)\")?\)")
LINK = re.compile(r"\[([^\]]+)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
BARE_URL = re.compile(r"(?<![\"'=(>])\bhttps?://[^\s<>()]+")
ALERT = re.compile(r"^\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*$", re.I)
YT_ID = re.compile(r"(?:youtu\.be/|v=|embed/|shorts/)([A-Za-z0-9_-]{6,20})")


def _esc(s):
    return html.escape(s, quote=False)


def inline(text):
    """Render inline markdown. Code spans are protected from other rules."""
    spans = []

    def stash(m):
        spans.append(m.group(1))
        return "\x00%d\x00" % (len(spans) - 1)

    text = INLINE_CODE.sub(stash, text)
    text = _esc(text)
    text = IMAGE.sub(
        lambda m: '<img src="%s" alt="%s" loading="lazy" decoding="async">'
                  % (html.escape(m.group(2), quote=True), html.escape(m.group(1), quote=True)),
        text,
    )
    text = LINK.sub(
        lambda m: '<a href="%s">%s</a>' % (html.escape(m.group(2), quote=True), m.group(1)),
        text,
    )
    text = BARE_URL.sub(lambda m: '<a href="%s">%s</a>' % (m.group(0), m.group(0)), text)
    text = BOLD.sub(lambda m: "<strong>%s</strong>" % m.group(1), text)
    text = ITALIC.sub(lambda m: "<em>%s</em>" % m.group(1), text)
    for idx, code in enumerate(spans):
        text = text.replace("\x00%d\x00" % idx, "<code>%s</code>" % _esc(code))
    return text


def _table(rows):
    head = rows[0]
    body = rows[2:]
    out = ['<div class="tablewrap"><table><thead><tr>']
    for cell in head:
        out.append("<th>%s</th>" % inline(cell))
    out.append("</tr></thead><tbody>")
    for row in body:
        out.append("<tr>")
        for cell in row:
            out.append("<td>%s</td>" % inline(cell))
        out.append("</tr>")
    out.append("</tbody></table></div>")
    return "".join(out)


def _split_row(line):
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [c.strip() for c in line.split("|")]


def render_markdown(text):
    lines = text.replace("\r\n", "\n").split("\n")
    out = []
    i = 0
    n = len(lines)

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # fenced code
        if stripped.startswith("```"):
            lang = stripped[3:].strip()
            i += 1
            buf = []
            while i < n and not lines[i].strip().startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1
            if lang.lower() in ("youtube", "video"):
                out.append(youtube_embed("\n".join(buf).strip()))
                continue
            cls = ' class="lang-%s"' % _esc(lang) if lang else ""
            out.append("<pre><code%s>%s</code></pre>" % (cls, _esc("\n".join(buf))))
            continue

        # horizontal rule
        if re.fullmatch(r"(-{3,}|\*{3,}|_{3,})", stripped):
            out.append("<hr>")
            i += 1
            continue

        # heading
        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            # the page owns h1, so the notes' own headings start one level down
            level = min(len(m.group(1)) + 1, 6)
            out.append("<h%d>%s</h%d>" % (level, inline(m.group(2).strip()), level))
            i += 1
            continue

        # table
        if "|" in stripped and i + 1 < n and re.fullmatch(r"[\s|:\-]+", lines[i + 1].strip()) \
                and "-" in lines[i + 1]:
            rows = []
            while i < n and "|" in lines[i]:
                rows.append(_split_row(lines[i]))
                i += 1
            if len(rows) >= 2:
                out.append(_table(rows))
                continue

        # blockquote, including GitHub alerts
        if stripped.startswith(">"):
            buf = []
            while i < n and lines[i].strip().startswith(">"):
                buf.append(re.sub(r"^\s*>\s?", "", lines[i]))
                i += 1
            kind = ""
            if buf:
                am = ALERT.match(buf[0].strip())
                if am:
                    kind = am.group(1).lower()
                    buf = buf[1:]
            cls = "quote alert alert--%s" % kind if kind else "quote"
            inner = render_markdown("\n".join(buf))
            label = ('<p class="alert-label">%s</p>' % kind.upper()) if kind else ""
            out.append('<blockquote class="%s">%s%s</blockquote>' % (cls, label, inner))
            continue

        # lists
        lm = re.match(r"^(\s*)([-*+]|\d+\.)\s+(.*)$", line)
        if lm:
            block, i = _list(lines, i, _indent_of(line))
            out.append(block)
            continue

        # paragraph
        buf = []
        while i < n and lines[i].strip() and not re.match(
                r"^\s*(#{1,6}\s|>|```|[-*+]\s|\d+\.\s)", lines[i]) \
                and not re.fullmatch(r"(-{3,}|\*{3,}|_{3,})", lines[i].strip()):
            buf.append(lines[i].strip())
            i += 1
        if buf:
            joined = " ".join(buf)
            solo = IMAGE.fullmatch(joined.strip())
            if solo:
                out.append(figure(solo.group(2), solo.group(1), solo.group(3)))
            else:
                out.append("<p>%s</p>" % inline(joined))
        else:
            i += 1

    return "\n".join(out)


def figure(src, alt, caption=None):
    cap = ""
    if caption:
        cap = "<figcaption>%s</figcaption>" % inline(caption)
    elif alt:
        cap = "<figcaption>%s</figcaption>" % inline(alt)
    return ('<figure class="fig"><img src="%s" alt="%s" loading="lazy" '
            'decoding="async">%s</figure>'
            % (html.escape(src, quote=True), html.escape(alt or "", quote=True), cap))


def youtube_embed(raw):
    """A plain lazy iframe: it needs no JavaScript and sets no cookie until played."""
    raw = raw.strip()
    m = YT_ID.search(raw)
    vid = m.group(1) if m else re.sub(r"[^A-Za-z0-9_-]", "", raw)
    if not vid:
        return ""
    return ('<div class="embed embed--video">'
            '<iframe src="https://www.youtube-nocookie.com/embed/%s" '
            'title="Video" loading="lazy" allowfullscreen '
            'allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" '
            'referrerpolicy="strict-origin-when-cross-origin"></iframe></div>' % vid)


def _list(lines, i, indent):
    n = len(lines)
    first = re.match(r"^(\s*)([-*+]|\d+\.)\s+(.*)$", lines[i])
    ordered = bool(re.fullmatch(r"\d+\.", first.group(2)))
    items = []
    while i < n:
        line = lines[i]
        if not line.strip():
            # a blank line only ends the list if the next content dedents out
            j = i + 1
            while j < n and not lines[j].strip():
                j += 1
            if j >= n or _indent_of(lines[j]) < indent or not re.match(
                    r"^\s*([-*+]|\d+\.)\s+", lines[j]):
                break
            i = j
            continue
        cur = _indent_of(line)
        if cur < indent:
            break
        m = re.match(r"^(\s*)([-*+]|\d+\.)\s+(.*)$", line)
        if not m or cur > indent:
            break
        buf = [m.group(3)]
        i += 1
        # continuation lines and nested lists belong to this item
        while i < n:
            if not lines[i].strip():
                nxt = i + 1
                while nxt < n and not lines[nxt].strip():
                    nxt += 1
                if nxt < n and _indent_of(lines[nxt]) > indent:
                    buf.append("")
                    i = nxt
                    continue
                break
            if _indent_of(lines[i]) > indent:
                buf.append(lines[i][indent:])
                i += 1
                continue
            break
        inner = "\n".join(buf)
        if re.search(r"^\s*([-*+]|\d+\.)\s+", inner, re.M) and "\n" in inner:
            items.append(render_markdown(inner))
        else:
            items.append(inline(" ".join(x.strip() for x in inner.split("\n") if x.strip())))
    tag = "ol" if ordered else "ul"
    body = "".join("<li>%s</li>" % it for it in items)
    return "<%s>%s</%s>" % (tag, body, tag), i


# --------------------------------------------------------------------------
# Content loading
# --------------------------------------------------------------------------

class Update(object):
    def __init__(self, meta, body, path):
        self.meta = meta
        self.body = body
        self.path = path
        self.slug = meta.get("slug") or self._slug()
        self.title = meta.get("title", "Untitled")
        self.track = meta.get("track", "main")
        self.tag = meta.get("tag", "")
        self.date = self._date()
        self.release_url = meta.get("release_url", "")
        self.summary = meta.get("summary", "")
        self.assets = meta.get("assets") or []
        self.prerelease = meta.get("prerelease", True)

    def _slug(self):
        base = os.path.basename(self.path)
        base = re.sub(r"\.md$", "", base)
        return re.sub(r"[^a-z0-9\-]+", "-", base.lower()).strip("-")

    def _date(self):
        raw = str(self.meta.get("date", ""))[:10]
        try:
            return dt.date(*[int(x) for x in raw.split("-")])
        except Exception:
            return dt.date(1970, 1, 1)

    @property
    def url(self):
        return "/updates/%s/" % self.slug

    def date_label(self):
        return "%d %s %d" % (self.date.day, self.date.strftime("%b"), self.date.year)


def split_frontmatter(text):
    text = text.replace("\r\n", "\n")
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    fm = text[3:end].strip("\n")
    body = text[end + 4:].lstrip("\n")
    meta = parse_yaml(fm) if fm.strip() else {}
    return (meta or {}), body


def load_site():
    path = os.path.join(CONTENT, "site.yaml")
    with open(path, encoding="utf-8") as fh:
        return parse_yaml(fh.read())


def load_updates():
    items = []
    if not os.path.isdir(UPDATES_DIR):
        return items
    for name in sorted(os.listdir(UPDATES_DIR)):
        if not name.endswith(".md"):
            continue
        path = os.path.join(UPDATES_DIR, name)
        with open(path, encoding="utf-8") as fh:
            meta, body = split_frontmatter(fh.read())
        items.append(Update(meta, body, path))
    items.sort(key=lambda u: (u.date, u.slug), reverse=True)
    return items


def kind_label(site, track):
    """Track name for a release, or a kind name for an announcement."""
    t = site.get("tracks", {}).get(track)
    if t:
        return t.get("name", track)
    k = (site.get("kinds") or {}).get(track)
    if k:
        return k.get("name", track)
    return track.replace("-", " ").title()


class Page(object):
    """A standalone page such as About. Same markdown, no release attached."""

    def __init__(self, meta, body, path):
        self.meta = meta
        self.body = body
        self.path = path
        self.slug = meta.get("slug") or re.sub(r"\.md$", "", os.path.basename(path))
        self.title = meta.get("title") or self.slug.replace("-", " ").capitalize()
        self.nav = meta.get("nav", self.title)
        self.order = int(meta.get("order", 100) or 100)
        self.description = meta.get("description", "")
        self.lede = meta.get("lede", "")

    @property
    def url(self):
        return "/%s/" % self.slug


def load_pages():
    items = []
    if not os.path.isdir(PAGES_DIR):
        return items
    for name in sorted(os.listdir(PAGES_DIR)):
        if not name.endswith(".md"):
            continue
        path = os.path.join(PAGES_DIR, name)
        with open(path, encoding="utf-8") as fh:
            meta, body = split_frontmatter(fh.read())
        items.append(Page(meta, body, path))
    items.sort(key=lambda p: (p.order, p.slug))
    return items


def latest_per_track(updates):
    out = {}
    for u in updates:
        if u.track not in out:
            out[u.track] = u
    return out


# --------------------------------------------------------------------------
# Formatting helpers
# --------------------------------------------------------------------------

def mib(nbytes):
    try:
        return "%.1f MiB" % (int(nbytes) / 1048576.0)
    except Exception:
        return ""


def mb_short(nbytes):
    try:
        return "%d MB" % round(int(nbytes) / 1048576.0)
    except Exception:
        return ""


def rel(depth, path):
    """Site-root-relative path turned into a document-relative one."""
    path = path.lstrip("/")
    return ("../" * depth) + path if depth else path


# --------------------------------------------------------------------------
# HTML shell
# --------------------------------------------------------------------------

def shell(site, depth, title, description, body, extra_class=""):
    css = rel(depth, "assets/site.css")
    js = rel(depth, "assets/field.js")
    home = rel(depth, "index.html") if depth else "#top"
    cls = ' class="%s"' % extra_class if extra_class else ""
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s</title>
<meta name="description" content="%(desc)s">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,100..900&family=Martian+Mono:wght@300;400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="%(css)s">
%(note)s
</head>
<body%(cls)s>

<div class="chrome">
  <a class="mark" href="%(home)s">
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 2 21.5 7.5v9L12 22 2.5 16.5v-9L12 2Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><path d="M12 22v-9.5M12 12.5 2.5 7.5M12 12.5l9.5-5" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" opacity=".55"/></svg>
    <b>Blender for Android</b>
  </a>
  <nav class="cnav">%(cnav)s</nav>
  <div class="flag">Unofficial build <i>&nbsp;/ not affiliated with the Blender Foundation</i></div>
</div>

%(body)s

<footer>
  <div class="wrap">
    <div class="fgrid">%(fcols)s</div>
    <div class="fbot">
      <span>%(disclaimer)s</span>
      <span>%(licence)s</span>
    </div>
  </div>
</footer>
<script src="%(js)s" defer></script>
</body>
</html>
""" % {
        "title": _esc(title),
        "desc": html.escape(description, quote=True),
        "css": css,
        "js": js,
        "home": home,
        "note": GENERATED_NOTE,
        "cls": cls,
        "cnav": chrome_nav(depth),
        "body": body,
        "fcols": footer_cols(site, depth),
        "disclaimer": _esc(site.get("disclaimer", "")),
        "licence": _esc(site.get("licence", "")),
    }


def chrome_nav(depth):
    links = ['<a href="%s">Log</a>' % rel(depth, "updates/index.html")]
    for pg in load_pages():
        links.append('<a href="%s">%s</a>'
                     % (rel(depth, pg.slug + "/index.html"), _esc(pg.nav)))
    return "".join(links)


def footer_cols(site, depth):
    out = []
    for track_id, track in site.get("tracks", {}).items():
        out.append(
            '<div class="fcol"><h2>%s</h2><a href="%s">Releases</a><a href="%s">Source</a></div>'
            % (_esc(track["name"]),
               html.escape(track["releases_url"], quote=True),
               html.escape(track["repo_url"], quote=True))
        )
    links = ['<a href="%s">Porting log</a>' % rel(depth, "updates/index.html"),
             '<a href="%s">Downloads</a>' % (rel(depth, "index.html") + "#download")]
    for pg in load_pages():
        links.append('<a href="%s">%s</a>'
                     % (rel(depth, pg.slug + "/index.html"), _esc(pg.nav)))
    out.append('<div class="fcol"><h2>This site</h2>%s</div>' % "".join(links))
    out.append(
        '<div class="fcol"><h2>Blender</h2>'
        '<a href="https://www.blender.org">blender.org</a>'
        '<a href="https://projects.blender.org">Upstream development</a></div>'
    )
    return "".join(out)


# --------------------------------------------------------------------------
# Page sections
# --------------------------------------------------------------------------

ICON_CHECK = ('<svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true">'
              '<path d="M4 12.5 9.5 18 20 6.5" stroke="currentColor" stroke-width="1.8" '
              'stroke-linecap="round" stroke-linejoin="round"/></svg>')
ICON_WARN = ('<svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true">'
             '<path d="M12 3.5 21 19H3l9-15.5Z" stroke="currentColor" stroke-width="1.7" '
             'stroke-linejoin="round"/><path d="M12 10v4m0 2.6v.2" stroke="currentColor" '
             'stroke-width="1.7" stroke-linecap="round"/></svg>')
ICON_DL = ('<svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true">'
           '<path d="M12 3v13m0 0 5-5m-5 5-5-5M4 21h16" stroke="currentColor" stroke-width="1.6" '
           'stroke-linecap="round" stroke-linejoin="round"/></svg>')
ICON_ARROW = ('<svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true">'
              '<path d="M4 12h15m0 0-5.5-5.5M19 12l-5.5 5.5" stroke="currentColor" '
              'stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>')
ICON_TICK_SM = ('<svg width="13" height="13" viewBox="0 0 24 24" fill="none" aria-hidden="true">'
                '<path d="M4 12.5 9.5 18 20 6.5" stroke="currentColor" stroke-width="2.6" '
                'stroke-linecap="round" stroke-linejoin="round"/></svg>')


def hero(site, latest):
    reqs = site.get("requirements", [])
    readout = "".join(
        '<div>%s<b>%s</b></div>' % (_esc(r["label"]), _esc(r["value"])) for r in reqs
    )
    return """
<header class="hero" id="top">
  <div class="field" id="field"><canvas id="cv" aria-hidden="true"></canvas></div>
  <div class="wrap">
    <div class="hero-grid">
      <ul class="index">
        <li><a href="#device"><em>01</em>Device</a></li>
        <li><a href="#builds"><em>02</em>Builds</a></li>
        <li><a href="#download"><em>03</em>Download</a></li>
        <li><a href="#updates"><em>04</em>Updates</a></li>
      </ul>
      <div>
        <h1 class="headline">Blender<br>on<br><span class="thin">Android</span></h1>
        <p class="standfirst">%(stand)s<br><b>%(disclaimer)s</b></p>
        <div class="actions">
          <a class="btn btn--primary" href="#download">Download %(dl)s</a>
          <a class="btn" href="#builds">Compare the two builds %(ar)s</a>
          <a class="btn" href="#updates">What's new %(ar)s</a>
        </div>
        <div class="readout">%(readout)s</div>
      </div>
    </div>
  </div>
  <div class="scrollcue">Scroll</div>
</header>
""" % {
        "stand": _esc(site.get("standfirst", "")),
        "disclaimer": _esc(site.get("disclaimer", "")),
        "dl": ICON_DL,
        "ar": ICON_ARROW,
        "readout": readout,
    }


def device_section(site):
    items = []
    for req in site.get("requirements", []):
        rid = req["id"]
        items.append("""
      <div class="check-item">
        <input type="checkbox" id="req-%(id)s">
        <label for="req-%(id)s">
          <span class="box">%(tick)s</span>
          <span><span class="t">%(title)s</span><span class="d">%(desc)s</span></span>
        </label>
      </div>""" % {
            "id": _esc(rid),
            "tick": ICON_TICK_SM,
            "title": _esc(req.get("check") or req["value"]),
            "desc": _esc(req["detail"]),
        })
    return """
<section id="device" class="checks">
  <div class="wrap">
    <div class="shead reveal">
      <h2>Will it run<br>on your device</h2>
      <p>%(lede)s</p>
    </div>
    <div class="check reveal">%(items)s
    </div>
    <div class="verdict reveal">
      <span class="wait">Confirm all three to continue</span>
      <span class="ok">Your device qualifies &mdash; choose a build below</span>
    </div>
  </div>
</section>
""" % {"items": "".join(items), "lede": _esc(site.get("device_lede", ""))}


def builds_section(site, latest, updates):
    cards = []
    for track_id, track in site.get("tracks", {}).items():
        u = latest.get(track_id)
        bullets = []
        for b in track.get("points", []):
            icon = ICON_WARN if b.get("warn") else ICON_CHECK
            lead = ('<b>%s</b> ' % _esc(b["lead"])) if b.get("lead") else ""
            bullets.append("<li>%s<span>%s%s</span></li>" % (icon, lead, _esc(b["text"])))
        sizes = ""
        if u and u.assets:
            vals = sorted(int(a["bytes"]) for a in u.assets if a.get("bytes"))
            nums = [mb_short(v).replace(" MB", "") for v in vals]
            sizes = "%s MB" % " / ".join(nums) if nums else ""
        stats = [
            ("Latest", u.date_label() if u else "-"),
            ("Size" if (u and len(u.assets) == 1) else "Sizes", sizes or "-"),
        ]
        # project total for this track, summed across every release on file
        total = sum(int(a.get("downloads") or 0)
                    for up in updates if up.track == track_id
                    for a in up.assets)
        if total:
            stats.append(("Downloads", "{:,}".format(total)))
        foot = "".join('<div class="stat">%s<b>%s</b></div>' % (_esc(k), _esc(v))
                       for k, v in stats)
        cards.append("""
      <article class="track">
        <h3>%(name)s</h3>
        <div class="who">%(who)s</div>
        <p class="lede">%(lede)s</p>
        <ul>%(bullets)s</ul>
        <div class="foot">%(foot)s</div>
      </article>""" % {
            "name": _esc(track["name"]),
            "who": _esc("%s &middot; %s" % (track["repo"], u.tag if u else "")).replace(
                "&amp;middot;", "&middot;"),
            "lede": _esc(track["lede"]),
            "bullets": "".join(bullets),
            "foot": foot,
        })
    return """
<section id="builds">
  <div class="wrap">
    <div class="shead reveal">
      <h2>One port,<br>two branches</h2>
      <p>%(lede)s</p>
    </div>
    <div class="tracks reveal">%(cards)s
    </div>
  </div>
</section>
""" % {"cards": "".join(cards), "lede": _esc(site.get("builds_lede", ""))}


def file_rows(site, latest, depth=0):
    rows = []
    order = list(site.get("tracks", {}).items())
    files = []
    for track_id, track in order:
        u = latest.get(track_id)
        if not u:
            continue
        for a in u.assets:
            files.append((track, u, a))
    # smallest first: the recommended starting point leads
    files.sort(key=lambda f: int(f[2].get("bytes") or 0))
    for idx, (track, u, a) in enumerate(files):
        sha = a.get("sha256") or ""
        if sha:
            hash_html = '<div class="hash"><b>SHA-256</b>%s</div>' % _esc(sha)
        else:
            hash_html = ('<div class="hash none"><b>SHA-256</b>not published for this '
                         'release &mdash; verify the signing certificate below instead</div>')
        primary = " btn--primary" if idx == 0 else ""
        meta = [track["name"], u.tag, "<b>%s</b>" % mib(a.get("bytes")), u.date_label()]
        if a.get("downloads"):
            meta.append("{:,} downloads".format(int(a["downloads"])))
        rows.append("""
      <div class="file">
        <div>
          <div class="nm">%(name)s</div>
          <div class="meta">%(meta)s</div>
        </div>
        <a class="btn%(primary)s" href="%(url)s">%(label)s %(dl)s</a>
        %(hash)s
      </div>""" % {
            "name": _esc(a["name"]),
            "meta": "".join("<span>%s</span>" % m for m in meta),
            "primary": primary,
            "url": html.escape(a.get("url") or u.release_url, quote=True),
            "label": _esc("Get %s" % a.get("label", "build")),
            "dl": ICON_DL,
            "hash": hash_html,
        })
    return "".join(rows)


def download_section(site, latest):
    steps = []
    for s in site.get("install_steps", []):
        steps.append("<li><h4>%s</h4><p>%s</p></li>" % (_esc(s["title"]), _esc(s["text"])))
    return """
<section id="download">
  <div class="wrap">
    <div class="shead reveal">
      <h2>Download</h2>
      <p>%(lede)s</p>
    </div>
    <div class="files reveal">%(files)s
    </div>
    <h3 class="minor">Installing</h3>
    <ol class="steps reveal">%(steps)s</ol>
    <div class="notice reveal">
      %(warn)s
      <div>
        <h3>Signing certificate, upstream builds</h3>
        <p class="fingerprint">%(fp)s</p>
        <p>%(note)s</p>
      </div>
    </div>
  </div>
</section>
""" % {
        "lede": _esc(site.get("download_lede", "")),
        "files": file_rows(site, latest),
        "steps": "".join(steps),
        "warn": ICON_WARN.replace('width="15" height="15"', 'width="26" height="26"'),
        "fp": _esc(site.get("signing_fingerprint", "")),
        "note": _esc(site.get("alpha_note", "")),
    }


def entry_html(site, u, depth=0, level=3):
    cls = {"main": "up", "s24": "dn"}.get(u.track, "nw")
    summary = u.summary or ""
    tag_html = "<b>%s</b>" % _esc(u.tag) if u.tag else ""
    return """
      <article class="entry reveal">
        <div class="when">%(date)s%(tag)s<span class="tag %(cls)s">%(track)s</span></div>
        <div>
          <h%(lvl)d><a href="%(url)s">%(title)s</a></h%(lvl)d>
          <p>%(summary)s</p>
          <a class="more" href="%(url)s">Read this update %(ar)s</a>
        </div>
      </article>""" % {
        "date": _esc(u.date_label()),
        "tag": tag_html,
        "cls": cls,
        "track": _esc(kind_label(site, u.track)),
        "url": rel(depth, u.url.lstrip("/") + "index.html"),
        "title": _esc(u.title),
        "summary": inline(summary),
        "lvl": level,
        "ar": ICON_ARROW,
    }


def updates_section(site, updates, limit):
    shown = updates[:limit]
    entries = "".join(entry_html(site, u) for u in shown)
    more = ""
    if len(updates) > limit:
        more = ('<a class="btn allupdates" href="updates/index.html">'
                'All %d updates %s</a>' % (len(updates), ICON_ARROW))
    return """
<section id="updates">
  <div class="wrap">
    <div class="shead reveal">
      <h2>Porting log</h2>
      <p>%(lede)s</p>
    </div>
    <div class="feed">%(entries)s</div>
    %(more)s
  </div>
</section>
""" % {"lede": _esc(site.get("updates_lede", "")), "entries": entries, "more": more}


# --------------------------------------------------------------------------
# Pages
# --------------------------------------------------------------------------

def build_home(site, updates, latest):
    body = (hero(site, latest)
            + "<main>"
            + device_section(site)
            + builds_section(site, latest, updates)
            + download_section(site, latest)
            + updates_section(site, updates, int(site.get("feed_on_home", 4)))
            + "</main>")
    return shell(site, 0, site["title"], site["description"], body)


def build_updates_index(site, updates):
    entries = "".join(entry_html(site, u, depth=1, level=2) for u in updates)
    body = """
<main class="page">
  <div class="wrap">
    <div class="pagehead">
      <h1>Porting log</h1>
      <p>%(lede)s</p>
    </div>
    <div class="feed">%(entries)s</div>
  </div>
</main>
""" % {"lede": _esc(site.get("updates_lede", "")), "entries": entries}
    return shell(site, 1, "Porting log - %s" % site["title"],
                 site.get("updates_lede", ""), body, "sub")


def strip_leading_title(body, title):
    """Drop the notes' own opening heading when the page header already says it."""
    lines = body.lstrip().split("\n")
    if not lines:
        return body
    m = re.match(r"^#{1,2}\s+(.*)$", lines[0].strip())
    if not m:
        return body
    def norm(s):
        return re.sub(r"[^a-z0-9]+", "", s.lower())
    head, want = norm(m.group(1)), norm(title)
    if head and (head in want or want in head):
        return "\n".join(lines[1:]).lstrip("\n")
    return body


def normalize_headings(md):
    """Shift headings so the document's own top level lands on h2.

    Authors write `#` or `##` for their first section depending on habit, and
    the page already owns the h1. Rebasing here means either habit produces a
    correct outline instead of jumping h1 to h3.
    """
    lines = (md or "").replace("\r\n", "\n").split("\n")
    levels, fenced = [], False
    for ln in lines:
        if ln.strip().startswith("```"):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = re.match(r"^(#{1,6})\s+\S", ln.strip())
        if m:
            levels.append(len(m.group(1)))
    if not levels:
        return md

    shift = 1 - min(levels)
    if shift == 0:
        return md

    out, fenced = [], False
    for ln in lines:
        if ln.strip().startswith("```"):
            fenced = not fenced
            out.append(ln)
            continue
        m = re.match(r"^(#{1,6})(\s+\S.*)$", ln.strip()) if not fenced else None
        if m:
            lvl = max(1, min(6, len(m.group(1)) + shift))
            out.append("#" * lvl + m.group(2))
        else:
            out.append(ln)
    return "\n".join(out)


def build_standalone(site, pg):
    lede = ('<p>%s</p>' % _esc(pg.lede)) if pg.lede else ""
    body = """
<main class="page">
  <div class="wrap">
    <div class="pagehead">
      <h1>%(title)s</h1>
      %(lede)s
    </div>
    <div class="prose">%(content)s</div>
  </div>
</main>
""" % {"title": _esc(pg.title), "lede": lede,
       "content": render_markdown(normalize_headings(strip_leading_title(pg.body, pg.title)))}
    return shell(site, 1, "%s - %s" % (pg.title, site["title"]),
                 pg.description or pg.lede or site["description"], body, "sub")


def build_post(site, u, updates, index):
    prev_u = updates[index + 1] if index + 1 < len(updates) else None
    next_u = updates[index - 1] if index > 0 else None

    files = []
    for a in u.assets:
        sha = a.get("sha256") or ""
        hash_html = ('<div class="hash"><b>SHA-256</b>%s</div>' % _esc(sha)) if sha else ""
        files.append("""
      <div class="file">
        <div>
          <div class="nm">%(name)s</div>
          <div class="meta"><span><b>%(size)s</b></span><span>%(label)s</span></div>
        </div>
        <a class="btn btn--primary" href="%(url)s">Download %(dl)s</a>
        %(hash)s
      </div>""" % {
            "name": _esc(a["name"]),
            "size": mib(a.get("bytes")),
            "label": _esc(a.get("label", "")),
            "url": html.escape(a.get("url") or u.release_url, quote=True),
            "dl": ICON_DL,
            "hash": hash_html,
        })

    nav = []
    if next_u:
        nav.append('<a class="pnav pnav--next" href="../%s/"><em>Newer</em>%s</a>'
                   % (next_u.slug, _esc(next_u.title)))
    if prev_u:
        nav.append('<a class="pnav pnav--prev" href="../%s/"><em>Older</em>%s</a>'
                   % (prev_u.slug, _esc(prev_u.title)))

    files_html = ('<div class="files postfiles">%s</div>' % "".join(files)) if files else ""
    source_html = ""
    if u.release_url:
        source_html = ('<p class="source">Originally published as '
                       '<a href="%s">%s on GitHub</a>.</p>'
                       % (html.escape(u.release_url, quote=True), _esc(u.tag or "the release")))

    body = """
<main class="page post">
  <div class="wrap">
    <a class="back" href="../index.html">%(ar)s Porting log</a>
    <article>
      <div class="posthead">
        <div class="when">%(date)s%(tag)s<span class="tag %(cls)s">%(track)s</span></div>
        <h1>%(title)s</h1>
      </div>
      %(files)s
      <div class="prose">%(content)s</div>
      %(source)s
    </article>
    <nav class="postnav">%(nav)s</nav>
  </div>
</main>
""" % {
        "ar": ICON_ARROW,
        "date": _esc(u.date_label()),
        "tag": ("<b>%s</b>" % _esc(u.tag)) if u.tag else "",
        "cls": {"main": "up", "s24": "dn"}.get(u.track, "nw"),
        "track": _esc(kind_label(site, u.track)),
        "title": _esc(u.title),
        "files": files_html,
        "content": render_markdown(normalize_headings(strip_leading_title(u.body, u.title))),
        "source": source_html,
        "nav": "".join(nav),
    }
    desc = u.summary or u.title
    return shell(site, 2, "%s - %s" % (u.title, site["title"]), desc, body, "sub")


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def write(path, text):
    d = os.path.dirname(path)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("  wrote %s" % os.path.relpath(path, ROOT).replace("\\", "/"))


def cmd_build(args):
    site = load_site()
    updates = load_updates()
    if not updates:
        print("warning: no updates found in content/updates/")
    latest = latest_per_track(updates)

    print("building %d update(s)" % len(updates))
    write(os.path.join(ROOT, "index.html"), build_home(site, updates, latest))
    write(os.path.join(OUT_UPDATES, "index.html"), build_updates_index(site, updates))

    # remove pages for updates that no longer exist
    keep = {u.slug for u in updates}
    if os.path.isdir(OUT_UPDATES):
        for name in os.listdir(OUT_UPDATES):
            p = os.path.join(OUT_UPDATES, name)
            if os.path.isdir(p) and name not in keep:
                shutil.rmtree(p)
                print("  removed stale %s" % name)

    for i, u in enumerate(updates):
        write(os.path.join(OUT_UPDATES, u.slug, "index.html"),
              build_post(site, u, updates, i))

    pages = load_pages()
    for pg in pages:
        write(os.path.join(ROOT, pg.slug, "index.html"), build_standalone(site, pg))
    prune_stale_pages({p.slug for p in pages})
    print("done")


def prune_stale_pages(keep):
    """Remove page directories whose markdown file is gone.

    Only directories holding an index.html this generator wrote are considered,
    so a hand-made folder in the repository root is never touched.
    """
    for name in os.listdir(ROOT):
        if name in keep or name.startswith(".") or name == "updates":
            continue
        target = os.path.join(ROOT, name)
        index = os.path.join(target, "index.html")
        if not os.path.isdir(target) or not os.path.isfile(index):
            continue
        try:
            with open(index, encoding="utf-8") as fh:
                if GENERATED_NOTE not in fh.read(4096):
                    continue
        except OSError:
            continue
        shutil.rmtree(target)
        print("  removed stale page %s" % name)


TEMPLATE = """---
title: %(title)s
track: %(track)s
tag: %(tag)s
date: %(date)s
release_url: %(release_url)s
summary: >
  %(summary)s
assets:
%(assets)s---

%(body)s
"""


def asset_block(assets):
    if not assets:
        return ("  - name: blender-full.apk\n"
                "    label: Full\n"
                "    bytes: 0\n"
                "    url: \n"
                "    sha256: \n")
    out = []
    for a in assets:
        out.append("  - name: %s\n" % a["name"])
        out.append("    label: %s\n" % a.get("label", ""))
        out.append("    bytes: %d\n" % int(a.get("bytes") or 0))
        out.append("    url: %s\n" % (a.get("url") or ""))
        out.append("    sha256: %s\n" % (a.get("sha256") or ""))
        if a.get("downloads") is not None:
            out.append("    downloads: %d\n" % int(a["downloads"]))
    return "".join(out)


def slug_for(date, track, tag):
    tag_part = re.sub(r"[^a-z0-9]+", "-", str(tag).lower()).strip("-")
    return "%s-%s-%s" % (date, track, tag_part)


def cmd_new(args):
    today = args.date or dt.date.today().isoformat()
    track = args.track or "news"
    title = args.title or ""
    # an announcement carries no tag and no downloads; a release scaffold does
    release = bool(args.tag) or track != "news"
    stem = args.tag or re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "untitled"
    slug = slug_for(today, track, stem)
    path = os.path.join(UPDATES_DIR, slug + ".md")
    if os.path.exists(path) and not args.force:
        sys.exit("refusing to overwrite %s (use --force)" % path)
    text = TEMPLATE % {
        "title": title,
        "track": track,
        "tag": args.tag or "",
        "date": today,
        "release_url": "",
        "summary": "One or two sentences for the feed.",
        "assets": asset_block(None) if release else "",
        "body": ("Write the release notes here as markdown.\n" if release
                 else "Write the announcement here as markdown.\n"),
    }
    write(path, text)
    print("\nFill it in, then run: python tools/build.py")


GH_TAG = re.compile(r"github\.com/([^/]+)/([^/]+)/releases/tag/([^/?#]+)")
GH_REPO = re.compile(r"github\.com/([^/]+)/([^/]+)/?$")
SHA_LINE = re.compile(r"\b([0-9a-f]{64})\b")


def fetch_json(url):
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "blenderandroid-site-build",
    })
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", "Bearer %s" % token)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        sys.exit("GitHub returned %s for %s\n%s" % (exc.code, url, exc.read()[:400]))
    except urllib.error.URLError as exc:
        sys.exit("could not reach GitHub: %s" % exc.reason)


def label_for(name):
    low = name.lower()
    if "lite" in low:
        return "Lite"
    if "full" in low:
        return "Full"
    return "APK"


def find_sha(body, asset_name):
    """Best effort, most reliable evidence first. Never guesses between candidates."""
    if not body:
        return ""

    # 1. sha256sum output: "<hash>  <filename>", either order
    for pat in (r"\b([0-9a-f]{64})\b[ \t]+\*?%s\b",
                r"\b%s\b[ \t:]+([0-9a-f]{64})\b"):
        m = re.search(pat % re.escape(asset_name), body, re.I)
        if m:
            return m.group(1).lower()

    # 2. a hash within the same block as the filename
    idx = body.find(asset_name)
    if idx != -1:
        window = body[max(0, idx - 400): idx + 400]
        m = SHA_LINE.search(window)
        if m:
            return m.group(1)

    # 3. exactly one hash in the whole body that is not the signing fingerprint
    found = [h for h in set(SHA_LINE.findall(body))
             if not re.search(r"SHA-256:\s*" + h, body)]
    if len(found) == 1:
        return found[0]
    return ""


def cmd_import(args):
    site = load_site()
    url = args.url
    m = GH_TAG.search(url)
    if m:
        owner, repo, tag = m.group(1), m.group(2), m.group(3)
        api = "https://api.github.com/repos/%s/%s/releases/tags/%s" % (owner, repo, tag)
    else:
        m = GH_REPO.search(url.rstrip("/"))
        if not m:
            sys.exit("expected a release URL or a repo URL, got: %s" % url)
        owner, repo = m.group(1), m.group(2)
        api = "https://api.github.com/repos/%s/%s/releases/latest" % (owner, repo)

    print("fetching %s" % api)
    data = fetch_json(api)

    full_name = "%s/%s" % (owner, repo)
    track = args.track
    if not track:
        for tid, t in site.get("tracks", {}).items():
            if t.get("repo", "").lower() == full_name.lower():
                track = tid
                break
    if not track:
        sys.exit("could not match %s to a track in content/site.yaml; pass --track"
                 % full_name)

    body = data.get("body") or ""
    assets = []
    for a in data.get("assets", []):
        assets.append({
            "name": a["name"],
            "label": label_for(a["name"]),
            "bytes": a["size"],
            "url": a["browser_download_url"],
            "sha256": find_sha(body, a["name"]),
            "downloads": a.get("download_count", 0),
        })

    date = (data.get("published_at") or "")[:10] or dt.date.today().isoformat()
    tag = data.get("tag_name", "")
    slug = slug_for(date, track, tag)
    path = os.path.join(UPDATES_DIR, slug + ".md")
    if os.path.exists(path) and not args.force:
        sys.exit("%s already exists (use --force to overwrite)" % path)

    title = args.title or data.get("name") or tag
    # the first real sentence of the notes makes a serviceable first summary
    summary = ""
    for line in body.splitlines():
        line = line.strip()
        if line and not line.startswith(("#", ">", "-", "*", "|", "`")):
            summary = re.sub(r"\*\*|`", "", line)
            break

    text = TEMPLATE % {
        "title": title,
        "track": track,
        "tag": tag,
        "date": date,
        "release_url": data.get("html_url", ""),
        "summary": summary or "Edit this summary; it is what the feed shows.",
        "assets": asset_block(assets),
        "body": body.strip() + "\n",
    }
    write(path, text)
    missing = [a["name"] for a in assets if not a["sha256"]]
    if missing:
        print("\n  note: no SHA-256 found in the notes for: %s" % ", ".join(missing))
        print("  the page will say so rather than invent one.")
    print("\nReview and hand-tune that file, then run: python tools/build.py")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd")

    sub.add_parser("build", help="regenerate the site (default)")

    p_new = sub.add_parser("new", help="scaffold an update or an announcement")
    p_new.add_argument("--track", default="", help="track id from site.yaml; omit for an announcement")
    p_new.add_argument("--tag", default="", help="release tag")
    p_new.add_argument("--title", default="", help="post title")
    p_new.add_argument("--date", default="", help="YYYY-MM-DD, defaults to today")
    p_new.add_argument("--force", action="store_true")

    p_imp = sub.add_parser("import", help="pull a GitHub release into an update")
    p_imp.add_argument("url", help="release URL, or repo URL for the latest release")
    p_imp.add_argument("--track", default="", help="override the track id")
    p_imp.add_argument("--title", default="", help="override the title")
    p_imp.add_argument("--force", action="store_true")

    args = ap.parse_args()
    if args.cmd == "new":
        cmd_new(args)
    elif args.cmd == "import":
        cmd_import(args)
    else:
        cmd_build(args)


if __name__ == "__main__":
    main()
